function res = climada_calibration_calcRMSE(files,orgS,rmv)

% Calculating of the RMSE for all shapefiles defined in files
% 
% MODULE:
%   flood
% NAME:
%   climada_calibration_calcRMSE
% PURPOSE:
%   
% CALLING SEQUENCE:
%   res = climada_calibration_calcRMSE(files)
% EXAMPLE:
%   climada_ls_multipleflow(lon,lat,elevation,25,1)
% INPUTS: 
%   files:   structure (files = dir(['path' '/*.shp']) which contains filepaths 
%            of shapefiles (generated by scriptFPCalibration, containing model-output)
%            with different flow path parameters sets (need to be defined in
%            filename)
%            shapefile need to include fields: length, area
%   orgS:    original shapefile (generated by climada_calibration_orgS2raster)
%            whith observed length and area fields. Need to have same
%            number of slides as model-output shape files
%       
% OPTIONAL INPUT PARAMETERS:
%   rmv:     in
% OUTPUTS:
%   res:    
% MODIFICATION HISTORY:
% Thomas Rölli, thomasroelli@gmail.com, 20180523, init

%check arguments
if ~exist('files'), return; end
if ~exist('orgS'), return; end
if ~exist('rmv'), rmv = []; end

%init output
res_cali = repmat(struct('resol',[]),1,numel(files));

for i=1:numel(files)
   fileparts = strsplit(files(i).name,'_');
   res_cali(i).resol = fileparts(1);
   %phi
   num_idx = regexp(fileparts{2},'\d');
   res_cali(i).phi = str2double(extractAfter(fileparts{2},num_idx(1)-1));
   %vmax
   num_idx = regexp(fileparts{3},'\d');
   res_cali(i).vmax = str2double(extractAfter(fileparts{3},num_idx(1)-1));
   %exp
   num_idx = regexp(fileparts{4},'\d');
   res_cali(i).exp = str2double(extractAfter(fileparts{4},num_idx(1)-1));
   %dH
   num_idx = regexp(fileparts{5},'\d');
   res_cali(i).dH = str2double(extractAfter(fileparts{5},num_idx(1)-1));
   %iT
   num_idx = regexp(fileparts{6},'\d');
   tmp_str = extractAfter(fileparts{6},num_idx(1)-1);
   res_cali(i).iT = str2double([tmp_str(1) '.' tmp_str(2:end)]);
   %perWTS
   num_idx = regexp([fileparts{7:end}],'\d');
   tmp_str = extractBetween([fileparts{7:end}],num_idx(1),num_idx(end));
   res_cali(i).perWT = tmp_str;
   
   %open corresponding caliS
   caliS = shaperead([files(i).folder filesep files(i).name]);
   
   %calculate RMSE for length
   obs = [orgS.length];%observed lengths
   pred = [caliS.length];%predicted lengths
   res_cali(i).rmse_lgt = sqrt(mean((obs-pred).^2,'omitnan'));
   
   %calculate RMSE for area
   obs = [orgS.area];%observed area
   pred = [caliS.area];%predicted area
   res_cali(i).rmse_area = sqrt(mean((obs-pred).^2,'omitnan'));
   
   %save source file
   res_cali(i).source = [files(i).folder filesep files(i).name];
end